//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILuffy.Halo
{
    
    
    /// <summary>
    /// The ILuffyConfig Configuration Section.
    /// </summary>
    public partial class ILuffyConfig : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ILuffyConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ILuffyConfigSectionName = "iLuffyConfig";
        
        /// <summary>
        /// The XML path of the ILuffyConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ILuffyConfigSectionPath = "iLuffyConfig";
        
        /// <summary>
        /// Gets the ILuffyConfig instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public static global::ILuffy.Halo.ILuffyConfig Instance
        {
            get
            {
                return ((global::ILuffy.Halo.ILuffyConfig)(global::System.Configuration.ConfigurationManager.GetSection(global::ILuffy.Halo.ILuffyConfig.ILuffyConfigSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ILuffy.Halo.ILuffyConfig.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::ILuffy.Halo.ILuffyConfig.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Instances Property
        /// <summary>
        /// The XML name of the <see cref="Instances"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string InstancesPropertyName = "instances";
        
        /// <summary>
        /// Gets or sets the Instances.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Instances.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ILuffy.Halo.ILuffyConfig.InstancesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ILuffy.Halo.InstanceCollection Instances
        {
            get
            {
                return ((global::ILuffy.Halo.InstanceCollection)(base[global::ILuffy.Halo.ILuffyConfig.InstancesPropertyName]));
            }
            set
            {
                base[global::ILuffy.Halo.ILuffyConfig.InstancesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ILuffy.Halo
{
    
    
    /// <summary>
    /// The InstanceElement Configuration Element.
    /// </summary>
    public partial class InstanceElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ILuffy.Halo.InstanceElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ILuffy.Halo.InstanceElement.NamePropertyName]));
            }
            set
            {
                base[global::ILuffy.Halo.InstanceElement.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Description Property
        /// <summary>
        /// The XML name of the <see cref="Description"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string DescriptionPropertyName = "description";
        
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Description.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ILuffy.Halo.InstanceElement.DescriptionPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Description
        {
            get
            {
                return ((string)(base[global::ILuffy.Halo.InstanceElement.DescriptionPropertyName]));
            }
            set
            {
                base[global::ILuffy.Halo.InstanceElement.DescriptionPropertyName] = value;
            }
        }
        #endregion
        
        #region TypeFullName Property
        /// <summary>
        /// The XML name of the <see cref="TypeFullName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string TypeFullNamePropertyName = "typeFullName";
        
        /// <summary>
        /// Gets or sets the TypeFullName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The TypeFullName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ILuffy.Halo.InstanceElement.TypeFullNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string TypeFullName
        {
            get
            {
                return ((string)(base[global::ILuffy.Halo.InstanceElement.TypeFullNamePropertyName]));
            }
            set
            {
                base[global::ILuffy.Halo.InstanceElement.TypeFullNamePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ILuffy.Halo
{
    
    
    /// <summary>
    /// A collection of InstanceElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ILuffy.Halo.InstanceElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ILuffy.Halo.InstanceCollection.InstanceElementPropertyName)]
    public partial class InstanceCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ILuffy.Halo.InstanceElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string InstanceElementPropertyName = "instanceElement";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override string ElementName
        {
            get
            {
                return global::ILuffy.Halo.InstanceCollection.InstanceElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ILuffy.Halo.InstanceCollection.InstanceElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ILuffy.Halo.InstanceElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ILuffy.Halo.InstanceElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ILuffy.Halo.InstanceElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ILuffy.Halo.InstanceElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ILuffy.Halo.InstanceElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ILuffy.Halo.InstanceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::ILuffy.Halo.InstanceElement this[int index]
        {
            get
            {
                return ((global::ILuffy.Halo.InstanceElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ILuffy.Halo.InstanceElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ILuffy.Halo.InstanceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::ILuffy.Halo.InstanceElement this[object name]
        {
            get
            {
                return ((global::ILuffy.Halo.InstanceElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ILuffy.Halo.InstanceElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="instanceElement">The <see cref="global::ILuffy.Halo.InstanceElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public void Add(global::ILuffy.Halo.InstanceElement instanceElement)
        {
            base.BaseAdd(instanceElement);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ILuffy.Halo.InstanceElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="instanceElement">The <see cref="global::ILuffy.Halo.InstanceElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public void Remove(global::ILuffy.Halo.InstanceElement instanceElement)
        {
            base.BaseRemove(this.GetElementKey(instanceElement));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ILuffy.Halo.InstanceElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ILuffy.Halo.InstanceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::ILuffy.Halo.InstanceElement GetItemAt(int index)
        {
            return ((global::ILuffy.Halo.InstanceElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ILuffy.Halo.InstanceElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ILuffy.Halo.InstanceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::ILuffy.Halo.InstanceElement GetItemByKey(string name)
        {
            return ((global::ILuffy.Halo.InstanceElement)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
