//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILuffy.IOP.I18N {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2016 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.6.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class CoreRS {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a CoreRS object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CoreRS() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("ILuffy.IOP.I18N.CoreRS", typeof(CoreRS).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Argument {0} is null.'.
        /// </summary>
        public static string ArgumentIsNull {
            get {
                return ResourceManager.GetString(ResourceNames.ArgumentIsNull, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The entry {0} is not found.'.
        /// </summary>
        public static string EntryNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.EntryNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Format key:{0} with parameters:{1} failed:{2}'.
        /// </summary>
        public static string FormatResourceKeyFailed {
            get {
                return ResourceManager.GetString(ResourceNames.FormatResourceKeyFailed, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Resource Key:{0}, parameters:'.
        /// </summary>
        public static string ResourceKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.ResourceKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The type full name of {0} is empty.'.
        /// </summary>
        public static string TypeFullNameIsEmpty {
            get {
                return ResourceManager.GetString(ResourceNames.TypeFullNameIsEmpty, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Argument {0} is null.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ArgumentIsNullFormat(object arg0) {
            return string.Format(_resourceCulture, ArgumentIsNull, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The entry {0} is not found.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string EntryNotFoundFormat(object arg0) {
            return string.Format(_resourceCulture, EntryNotFound, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Format key:{0} with parameters:{1} failed:{2}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string FormatResourceKeyFailedFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, FormatResourceKeyFailed, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Resource Key:{0}, parameters:'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ResourceKeyFormatFormat(object arg0) {
            return string.Format(_resourceCulture, ResourceKeyFormat, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The type full name of {0} is empty.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string TypeFullNameIsEmptyFormat(object arg0) {
            return string.Format(_resourceCulture, TypeFullNameIsEmpty, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ArgumentIsNull'.
            /// </summary>
            public const string ArgumentIsNull = "ArgumentIsNull";
            
            /// <summary>
            /// Stores the resource name 'EntryNotFound'.
            /// </summary>
            public const string EntryNotFound = "EntryNotFound";
            
            /// <summary>
            /// Stores the resource name 'FormatResourceKeyFailed'.
            /// </summary>
            public const string FormatResourceKeyFailed = "FormatResourceKeyFailed";
            
            /// <summary>
            /// Stores the resource name 'ResourceKeyFormat'.
            /// </summary>
            public const string ResourceKeyFormat = "ResourceKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'TypeFullNameIsEmpty'.
            /// </summary>
            public const string TypeFullNameIsEmpty = "TypeFullNameIsEmpty";
        }
    }
}
